<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_WebwinkelKeur
 * @author        Magmodules <info@magmodules.eu>
 * @copyright     Copyright (c) 2017 (http://www.magmodules.eu)
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$webwinkelconnect_id = (int) Mage::getStoreConfig('webwinkelconnect/general/api_id');
$enabled = Mage::getStoreConfig('webwinkelconnect/general/enabled');
$js_enabled = Mage::getStoreConfig('webwinkelconnect/frontend/enabled');
?>
<?php if ($webwinkelconnect_id && $js_enabled && $enabled): ?>
    <script type="text/javascript">
        (function () {
            _webwinkelkeur_id = <?php echo $webwinkelconnect_id; ?>;
            var js = document.createElement("script");
            js.type = "text/javascript";
            js.async = true;
            js.src = "//www.webwinkelkeur.nl/js/sidebar.js";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(js, s);
        })();
    </script>
<?php endif; ?>	